version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: turbokeys-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: turbokeys
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - turbokeys-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: turbokeys-backend
    environment:
      NODE_ENV: production
      PORT: 8080
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production
      JWT_EXPIRES_IN: 7d
      SESSION_SECRET: your_session_secret_here_change_in_production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/turbokeys?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - turbokeys-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: turbokeys-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - turbokeys-network

volumes:
  mongodb_data:

networks:
  turbokeys-network:
    driver: bridge
